In [1]:
import numpy as np

In [124]:
arr_2d=np.array([[1,2,3],[4,5,6],[8,9,0]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [151]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [154]:
arr_2d[1:,:2]

array([[4, 5],
       [8, 9]])

In [142]:
arr=np.array([[1,2],['string'],[7,8]])
arr

array([list([1, 2]), list(['string']), list([7, 8])], dtype=object)

In [129]:
arr[1]

'string'

In [130]:
arr[0][1]

2

In [143]:
arr[0,0]

IndexError: too many indices for array

In [158]:
arr=np.arange(50).reshape(5,10)


In [159]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [164]:
# to get 33,34 values alone

arr[3,3:5]

array([33, 34])

In [156]:
arr.reshape(3,10)

ValueError: cannot reshape array of size 3 into shape (3,10)

In [7]:
a=np.ones(2)
a

array([ 1.,  1.])

In [11]:
b=np.zeros((2,4))
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [13]:
c=np.linspace(2,5,9)
c

array([ 2.   ,  2.375,  2.75 ,  3.125,  3.5  ,  3.875,  4.25 ,  4.625,  5.   ])

In [23]:
d=np.eye(6)
d

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [25]:
e=np.random.rand(0,1)
e

array([], shape=(0, 1), dtype=float64)

In [28]:
np.random.rand(5)

array([ 0.19580282,  0.44147111,  0.7304974 ,  0.2504265 ,  0.71318898])

In [41]:
g=np.random.rand(5,2)
g

array([[ 0.14228011,  0.49258095],
       [ 0.90401464,  0.03750002],
       [ 0.40091237,  0.41400103],
       [ 0.62598026,  0.88077374],
       [ 0.03272623,  0.2208547 ]])

In [31]:
np.random.randn(5)

array([-1.76749173,  1.35478181,  0.62350723, -2.10969809,  0.22125512])

In [36]:
np.random.randint(1,100,10)

array([17, 57, 38, 59, 60, 94, 36, 90, 32, 87])

In [39]:
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [50]:
h=g.reshape(2,5)
h

array([[ 0.14228011,  0.49258095,  0.90401464,  0.03750002,  0.40091237],
       [ 0.41400103,  0.62598026,  0.88077374,  0.03272623,  0.2208547 ]])

In [46]:
g.argmax()

2

In [47]:
g.argmin()

8

In [53]:
from numpy.random import randint

In [99]:
randint(8,10)

8

### Diff between list and numpy array

In [102]:
my_list=[1,2,3,4]
my_list[1:3]

[2, 3]

In [103]:
my_list[1:3]=100

TypeError: can only assign an iterable

In [109]:
my_lis=np.arange(1,10)
my_lis[1:3]
my_lis

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
my_lis[1:3]=100 #broad casting
my_lis

array([  1, 100, 100,   4,   5,   6,   7,   8,   9])

### Slicing effect

In [111]:
my_lis

array([  1, 100, 100,   4,   5,   6,   7,   8,   9])

In [113]:
my_lis1=my_lis[5:]
my_lis1

array([6, 7, 8, 9])

In [114]:
my_lis1[:]=2000

In [115]:
my_lis1

array([2000, 2000, 2000, 2000])

In [116]:
my_lis

array([   1,  100,  100,    4,    5, 2000, 2000, 2000, 2000])

### copy of array without reference

In [117]:
my_lis

array([   1,  100,  100,    4,    5, 2000, 2000, 2000, 2000])

In [120]:
my_lis_copy= my_lis.copy()
my_lis_copy
my_lis_copy[:]=555
my_lis_copy

array([555, 555, 555, 555, 555, 555, 555, 555, 555])

In [121]:
my_lis

array([   1,  100,  100,    4,    5, 2000, 2000, 2000, 2000])

### operations